scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  PropertySortOrder:
    enabled: false
  LeadingZero:
    enabled: false
  Shorthand:
    enabled: false
  QualifyingElement:
    enabled: false
  NestingDepth:
    max_depth: 6
  SelectorDepth:
    max_depth: 6
  PlaceholderInExtend:
    enabled: false

  Indentation:
    severity: warning
    width: 2