# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ee13682168d9ff51560dd9092db71501abc7288b6ee380bd6c3ddb7ff11f7546193c8d11d769d520610293fb54153d2af74120d5270a0c37d00d9a157ace984

test:
  secret_key_base: dc02e1bf5efdfd3824b6ff99057363d3d02a31e390192b3255e5ffc6e2e9962d8944152cee855874aec2ecbed889b6ebacb55b8686116dba07fcba6227386f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
